SUMMARY = "AWS SDK for Go (subset)"
HOMEPAGE = "http://aws.amazon.com/sdk-for-go/"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://${GO_SRCROOT}/LICENSE.txt;md5=3b83ef96387f14655fc854ddc3c6bd57"
GO_SRCROOT = "github.com/aws/aws-sdk-go"
SRC_URI = "git://${GO_SRCROOT}"
SRCREV = "${AUTOREV}"
PV="1.0+git${SRCPV}"

export GO15VENDOREXPERIMENT = "1"

DEPENDS = "golang-stretchr-testify"

inherit golang

GO_PACKAGES = "\
    github.com/aws/aws-sdk-go \
    github.com/aws/aws-sdk-go/aws \
    github.com/aws/aws-sdk-go/aws/awserr \
    github.com/aws/aws-sdk-go/aws/awsutil \
    github.com/aws/aws-sdk-go/aws/client \
    github.com/aws/aws-sdk-go/aws/client/metadata \
    github.com/aws/aws-sdk-go/aws/corehandlers \
    github.com/aws/aws-sdk-go/aws/credentials \
    github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds \
    github.com/aws/aws-sdk-go/aws/credentials/stscreds \
    github.com/aws/aws-sdk-go/aws/defaults \
    github.com/aws/aws-sdk-go/aws/ec2metadata \
    github.com/aws/aws-sdk-go/aws/request \
    github.com/aws/aws-sdk-go/aws/session \
    github.com/aws/aws-sdk-go/private/endpoints \
    github.com/aws/aws-sdk-go/private/model \
    github.com/aws/aws-sdk-go/private/model/api \
    github.com/aws/aws-sdk-go/private/model/cli/api-info \
    github.com/aws/aws-sdk-go/private/model/cli/gen-api \
    github.com/aws/aws-sdk-go/private/model/cli/gen-endpoints \
    github.com/aws/aws-sdk-go/private/protocol/ec2query \
    github.com/aws/aws-sdk-go/private/protocol/json/jsonutil \
    github.com/aws/aws-sdk-go/private/protocol/jsonrpc \
    github.com/aws/aws-sdk-go/private/protocol/query \
    github.com/aws/aws-sdk-go/private/protocol/query/queryutil \
    github.com/aws/aws-sdk-go/private/protocol/rest \
    github.com/aws/aws-sdk-go/private/protocol/restjson \
    github.com/aws/aws-sdk-go/private/protocol/restxml \
    github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil \
    github.com/aws/aws-sdk-go/private/signer/v2 \
    github.com/aws/aws-sdk-go/private/signer/v4 \
    github.com/aws/aws-sdk-go/private/util \
    github.com/aws/aws-sdk-go/private/waiter \
    github.com/aws/aws-sdk-go/service \
    github.com/aws/aws-sdk-go/service/apigateway \
    github.com/aws/aws-sdk-go/service/apigateway/apigatewayiface \
    github.com/aws/aws-sdk-go/service/autoscaling \
    github.com/aws/aws-sdk-go/service/autoscaling/autoscalingiface \
    github.com/aws/aws-sdk-go/service/cloudformation \
    github.com/aws/aws-sdk-go/service/cloudformation/cloudformationiface \
    github.com/aws/aws-sdk-go/service/cloudfront \
    github.com/aws/aws-sdk-go/service/cloudfront/cloudfrontiface \
    github.com/aws/aws-sdk-go/service/cloudfront/sign \
    github.com/aws/aws-sdk-go/service/cloudhsm \
    github.com/aws/aws-sdk-go/service/cloudhsm/cloudhsmiface \
    github.com/aws/aws-sdk-go/service/cloudsearch \
    github.com/aws/aws-sdk-go/service/cloudsearch/cloudsearchiface \
    github.com/aws/aws-sdk-go/service/cloudsearchdomain \
    github.com/aws/aws-sdk-go/service/cloudsearchdomain/cloudsearchdomainiface \
    github.com/aws/aws-sdk-go/service/cloudtrail \
    github.com/aws/aws-sdk-go/service/cloudtrail/cloudtrailiface \
    github.com/aws/aws-sdk-go/service/cloudwatch \
    github.com/aws/aws-sdk-go/service/cloudwatch/cloudwatchiface \
    github.com/aws/aws-sdk-go/service/cloudwatchlogs \
    github.com/aws/aws-sdk-go/service/cloudwatchlogs/cloudwatchlogsiface \
    github.com/aws/aws-sdk-go/service/codecommit \
    github.com/aws/aws-sdk-go/service/codecommit/codecommitiface \
    github.com/aws/aws-sdk-go/service/codedeploy \
    github.com/aws/aws-sdk-go/service/codedeploy/codedeployiface \
    github.com/aws/aws-sdk-go/service/codepipeline \
    github.com/aws/aws-sdk-go/service/codepipeline/codepipelineiface \
    github.com/aws/aws-sdk-go/service/cognitoidentity \
    github.com/aws/aws-sdk-go/service/cognitoidentity/cognitoidentityiface \
    github.com/aws/aws-sdk-go/service/cognitosync \
    github.com/aws/aws-sdk-go/service/cognitosync/cognitosynciface \
    github.com/aws/aws-sdk-go/service/configservice \
    github.com/aws/aws-sdk-go/service/configservice/configserviceiface \
    github.com/aws/aws-sdk-go/service/datapipeline \
    github.com/aws/aws-sdk-go/service/datapipeline/datapipelineiface \
    github.com/aws/aws-sdk-go/service/devicefarm \
    github.com/aws/aws-sdk-go/service/devicefarm/devicefarmiface \
    github.com/aws/aws-sdk-go/service/directconnect \
    github.com/aws/aws-sdk-go/service/directconnect/directconnectiface \
    github.com/aws/aws-sdk-go/service/directoryservice \
    github.com/aws/aws-sdk-go/service/directoryservice/directoryserviceiface \
    github.com/aws/aws-sdk-go/service/dynamodb \
    github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute \
    github.com/aws/aws-sdk-go/service/dynamodb/dynamodbiface \
    github.com/aws/aws-sdk-go/service/dynamodbstreams \
    github.com/aws/aws-sdk-go/service/dynamodbstreams/dynamodbstreamsiface \
    github.com/aws/aws-sdk-go/service/ec2 \
    github.com/aws/aws-sdk-go/service/ec2/ec2iface \
    github.com/aws/aws-sdk-go/service/ecs \
    github.com/aws/aws-sdk-go/service/ecs/ecsiface \
    github.com/aws/aws-sdk-go/service/efs \
    github.com/aws/aws-sdk-go/service/efs/efsiface \
    github.com/aws/aws-sdk-go/service/elasticache \
    github.com/aws/aws-sdk-go/service/elasticache/elasticacheiface \
    github.com/aws/aws-sdk-go/service/elasticbeanstalk \
    github.com/aws/aws-sdk-go/service/elasticbeanstalk/elasticbeanstalkiface \
    github.com/aws/aws-sdk-go/service/elasticsearchservice \
    github.com/aws/aws-sdk-go/service/elasticsearchservice/elasticsearchserviceiface \
    github.com/aws/aws-sdk-go/service/elastictranscoder \
    github.com/aws/aws-sdk-go/service/elastictranscoder/elastictranscoderiface \
    github.com/aws/aws-sdk-go/service/elb \
    github.com/aws/aws-sdk-go/service/elb/elbiface \
    github.com/aws/aws-sdk-go/service/emr \
    github.com/aws/aws-sdk-go/service/emr/emriface \
    github.com/aws/aws-sdk-go/service/firehose \
    github.com/aws/aws-sdk-go/service/firehose/firehoseiface \
    github.com/aws/aws-sdk-go/service/glacier \
    github.com/aws/aws-sdk-go/service/glacier/glacieriface \
    github.com/aws/aws-sdk-go/service/iam \
    github.com/aws/aws-sdk-go/service/iam/iamiface \
    github.com/aws/aws-sdk-go/service/inspector \
    github.com/aws/aws-sdk-go/service/inspector/inspectoriface \
    github.com/aws/aws-sdk-go/service/iot \
    github.com/aws/aws-sdk-go/service/iot/iotiface \
    github.com/aws/aws-sdk-go/service/iotdataplane \
    github.com/aws/aws-sdk-go/service/iotdataplane/iotdataplaneiface \
    github.com/aws/aws-sdk-go/service/kinesis \
    github.com/aws/aws-sdk-go/service/kinesis/kinesisiface \
    github.com/aws/aws-sdk-go/service/kms \
    github.com/aws/aws-sdk-go/service/kms/kmsiface \
    github.com/aws/aws-sdk-go/service/lambda \
    github.com/aws/aws-sdk-go/service/lambda/lambdaiface \
    github.com/aws/aws-sdk-go/service/machinelearning \
    github.com/aws/aws-sdk-go/service/machinelearning/machinelearningiface \
    github.com/aws/aws-sdk-go/service/marketplacecommerceanalytics \
    github.com/aws/aws-sdk-go/service/marketplacecommerceanalytics/marketplacecommerceanalyticsiface \
    github.com/aws/aws-sdk-go/service/mobileanalytics \
    github.com/aws/aws-sdk-go/service/mobileanalytics/mobileanalyticsiface \
    github.com/aws/aws-sdk-go/service/opsworks \
    github.com/aws/aws-sdk-go/service/opsworks/opsworksiface \
    github.com/aws/aws-sdk-go/service/rds \
    github.com/aws/aws-sdk-go/service/rds/rdsiface \
    github.com/aws/aws-sdk-go/service/redshift \
    github.com/aws/aws-sdk-go/service/redshift/redshiftiface \
    github.com/aws/aws-sdk-go/service/route53 \
    github.com/aws/aws-sdk-go/service/route53/route53iface \
    github.com/aws/aws-sdk-go/service/route53domains \
    github.com/aws/aws-sdk-go/service/route53domains/route53domainsiface \
    github.com/aws/aws-sdk-go/service/s3 \
    github.com/aws/aws-sdk-go/service/s3/s3iface \
    github.com/aws/aws-sdk-go/service/s3/s3manager \
    github.com/aws/aws-sdk-go/service/ses \
    github.com/aws/aws-sdk-go/service/ses/sesiface \
    github.com/aws/aws-sdk-go/service/simpledb \
    github.com/aws/aws-sdk-go/service/simpledb/simpledbiface \
    github.com/aws/aws-sdk-go/service/sns \
    github.com/aws/aws-sdk-go/service/sns/snsiface \
    github.com/aws/aws-sdk-go/service/sqs \
    github.com/aws/aws-sdk-go/service/sqs/sqsiface \
    github.com/aws/aws-sdk-go/service/ssm \
    github.com/aws/aws-sdk-go/service/ssm/ssmiface \
    github.com/aws/aws-sdk-go/service/storagegateway \
    github.com/aws/aws-sdk-go/service/storagegateway/storagegatewayiface \
    github.com/aws/aws-sdk-go/service/sts \
    github.com/aws/aws-sdk-go/service/sts/stsiface \
    github.com/aws/aws-sdk-go/service/support \
    github.com/aws/aws-sdk-go/service/support/supportiface \
    github.com/aws/aws-sdk-go/service/swf \
    github.com/aws/aws-sdk-go/service/swf/swfiface \
    github.com/aws/aws-sdk-go/service/waf \
    github.com/aws/aws-sdk-go/service/waf/wafiface \
    github.com/aws/aws-sdk-go/service/workspaces \
    github.com/aws/aws-sdk-go/service/workspaces/workspacesiface \
"
